USE IPSMejoraTuSalud;

CREATE TABLE Medico(
	Cedula INT NOT NULL IDENTITY PRIMARY KEY,
	NombreS VARCHAR(64) NOT NULL,
	Apellidos VARCHAR(64) NOT NULL,
	Especialidad VARCHAR(32) NOT NULL,
	SalarioCita FLOAT NOT NULL,
	AñosExperiencia INT NOT NULL
);

CREATE TABLE Paciente(
	Cedula INT NOT NULL IDENTITY PRIMARY KEY,
	Nombres VARCHAR(64) NOT NULL,
	Apellidos VARCHAR(64) NOT NULL,
	FechaNto TIMESTAMP NOT NULL,
	Direccion VARCHAR(64) NOT NULL,
	Telefono INT NOT NULL,
	Email VARCHAR(32) NOT NULL,
	FechaRegistro TIMESTAMP DEFAULT GETDATE() NOT NULL,
);

CREATE TABLE Consulta(
	Id INT NOT NULL PRIMARY KEY,
	Cedula INT NOT NULL,
	HoraInicio TIMESTAMP DEFAULT GETDATE() NOT NULL,
	HoraFinal TIMESTAMP  NULL,
	MedicoResponsable INT FOREIGN KEY REFERENCES Medico(Cedula),
	PacienteSolicitante INT FOREIGN KEY REFERENCES Paciente(Cedula)
);
