//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpioFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public int Cedula { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFinal { get; set; }
        public Nullable<int> MedicoResponsable { get; set; }
        public Nullable<int> PacienteSolicitante { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
